# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\"K\n\x12\x43reateOrderRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12 \n\x05items\x18\x02 \x03(\x0b\x32\x11.orders.OrderItem\"U\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x02\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\":\n\x11OrderListResponse\x12%\n\x06orders\x18\x01 \x03(\x0b\x32\x15.orders.OrderResponse2\xce\x01\n\x0cOrderService\x12@\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponse\x12:\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponse\x12@\n\nListOrders\x12\x17.orders.GetOrderRequest\x1a\x19.orders.OrderListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEM']._serialized_start=24
  _globals['_ORDERITEM']._serialized_end=88
  _globals['_CREATEORDERREQUEST']._serialized_start=90
  _globals['_CREATEORDERREQUEST']._serialized_end=165
  _globals['_ORDERRESPONSE']._serialized_start=167
  _globals['_ORDERRESPONSE']._serialized_end=252
  _globals['_GETORDERREQUEST']._serialized_start=254
  _globals['_GETORDERREQUEST']._serialized_end=289
  _globals['_ORDERLISTRESPONSE']._serialized_start=291
  _globals['_ORDERLISTRESPONSE']._serialized_end=349
  _globals['_ORDERSERVICE']._serialized_start=352
  _globals['_ORDERSERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
